name: pheasant_assets
description: A starting point for Dart libraries or applications.
version: 0.1.0-alpha
repository: https://github.com/pheasantframework/pheasant_assets

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  csslib: ^1.0.0
  sass: ^1.69.7
  pheasant_meta: ^0.1.0-alpha
  # path: ^1.8.0

dependency_overrides: 
  pheasant_meta:
    path: ../pheasant_meta

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0

